### ISSUE TITLE
Doesn't seem to work at all anymore

### ISSUE THREAD

**Issue by markadrake** [asonawalla/FBEraser#18]
Here is a screenshot

![image](https://cloud.githubusercontent.com/assets/713355/15079238/5dc8b1c0-1385-11e6-9c79-4fb03f11ef6e.png)

**Comment by markadrake** [comment]
Starting on line 84 you'll want to update to the aria-label to data-tooltip-content.

`# Priority: highlights, allowed, hidden
        menu_button = soup.find('a', {'data-tooltip-content': 'Highlighted on Timeline'})
        if menu_button is None:
            menu_button = soup.find('a', {'data-tooltip-content': 'Allowed on Timeline'})
        if menu_button is None:
            menu_button = soup.find('a', {'data-tooltip-content': 'Hidden from Timeline'})
        if menu_button is None:
            menu_button = soup.find('a', {'data-tooltip-content': 'Shown on Timeline'})
`

**Comment by asonawalla** [comment]
That's not surprising at all; I don't think anyone's been using this for a while, and it is, after all, a UI-type hack.

I'll try to hack at it at point this week, but alternately I'd be happy to review and accept a pull request.

**Comment by ffineis** [comment]
I'm no web dev, far from it - I've just been noticing that when finding the 'allowed on timeline', 'edit',... buttons upon first getting to the activity page, the driver's getting confused on the 'friend requests' element. I tried searching for the menu_button in the correct div element, I still get an issue: Element is not clickable at point ([x],[y]). Other element would receive the click: <div class="_2n_9"></div>"... 

Besides that, I've been having luck doing the following (although this is not a coherent fix):

 `menu_button = soup.find_all("div", {"class":"fbTimelineLogBody"})[0].find('a', {'data-tooltip-content': 'Allowed on Timeline'})`

And then launching the JS console within the Firefox browser (launching the JS console removes the blue header on top of the FB screen, so as to avoid the Friend Request button issue.)

**Comment by Zyscandinavian** [comment]
Hello friends!
I have this problem as well! I've updated the script following fineiskid and markadrake's indication, however it still doesn't work. (by the way, how do I block Friend Requests by opening JS console? How do I open JS console in the first place, in Firefox?)

Is there any plan for further updates?

**Comment by mayday77** [comment]
Please enter Facebook login email: lol@lol.com
Password: 
Traceback (most recent call last):
  File "./FBEraser.py", line 129, in <module>
    eraser = Eraser(email=email, password=password, wait=args.wait)
  File "./FBEraser.py", line 24, in __init__
    self.driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
